site_name: Documentation
site_description: Tài liệu dự án
site_author: Vũ Văn Nghĩa

theme:
  name: material
  palette:
    # Palette selection for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Chuyển sang chế độ tối

    # Palette selection for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Chuyển sang chế độ sáng
  features:
    - navigation.footer
    - navigation.keyboard

plugins:
  - search:
      lang: vi
  - mkdocs-nav-weight

markdown_extensions:
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
