flowchart TD
    Client(["NextJS"])
    Gateway{"Kong API Gateway"}
    Client <-->|"request"| Gateway

    subgraph Databases [Databases & Storage]
        SupabaseDB[("Supabase")]
        NeonDB_Setting[("Neon Postgres")]
        Pinecone[("Pinecone")]
        Qdrant[("Qdrant")]
        NeonDB_Phapdien[("Neon Postgres")]
        R2[("Cloudflare R2")]

        R2 ~~~ Qdrant ~~~ Pinecone ~~~ NeonDB_Phapdien
    end

    Broker[["Kafka, RabbitMQ"]]
    Redis[("Redis & BullMQ")]

    subgraph CoreDomain [Core Subdomain]
        ConvService["Conversation Service"]
        ChatbotService["Chatbot Service"]
    end

    subgraph SupportDomain [Supporting Subdomain]
        DocService["Document Service"]
    end

    subgraph GenericDomain [Generic Subdomain]
        AuthService["Auth Service"]
        SettingService["Setting Service"]
        PaymentSvc["Payment Service"]
    end



    LLM(("Large Language Model"))
    Payment(("Cổng Thanh Toán"))

    Gateway -->|"Auth, MFA, Profile, Avatar"| AuthService
    Gateway -->|"GET/POST"| SettingService
    Gateway -->|"Thanh toán"| PaymentSvc
    Gateway -->|"Upload File (VIP)"| DocService
    Gateway <-->|"Request/Response"| ConvService

    AuthService <-->|"Đọc/Ghi/Upload"| SupabaseDB
    SettingService <-->|"RESTful API"| NeonDB_Setting

    PaymentSvc <-->|"Xử lý giao dịch"| Payment
    PaymentSvc -->|"Publish Event: payment_success"| Broker
    PaymentSvc <-->|"Lên lịch tác vụ (BullMQ)"| Redis

    ChatbotService <-->|"Event: Chat & Share"| Broker
    ConvService <-->|"Event: Chat & Share"| Broker

    DocService -->|"Lưu file vật lý"| R2
    DocService -->|"Trích xuất & Vector hóa (Docling)"| Qdrant

    ConvService <-->|"gRPC"| ChatbotService

    ChatbotService <-->|"Truy vấn VBPL"| Pinecone
    ChatbotService <-->|"Truy vấn Pháp điển"| NeonDB_Phapdien
    ChatbotService <-->|"Truy vấn File VIP"| Qdrant
    ChatbotService <-->|"call"| LLM

    Broker -.->|"Consume Event: payment_success"| DocService
    Broker -.->|"Consume Event: payment_success"| ConvService

    classDef core fill:#e1f5fe,stroke:#03a9f4,stroke-width:2px,color:#000
    classDef support fill:#f3e5f5,stroke:#9c27b0,stroke-width:2px,color:#000
    classDef generic fill:#fff3e0,stroke:#ff9800,stroke-width:2px,color:#000
    classDef db fill:#e8f5e9,stroke:#4caf50,stroke-width:2px,color:#000

    class ConvService,ChatbotService core
    class DocService support
    class AuthService,SettingService,PaymentSvc generic
    class SupabaseDB,NeonDB_Setting,NeonDB_Phapdien,Pinecone,Qdrant,R2 db

    style Redis fill:#ffebee,stroke:#d32f2f,stroke-width:2px,color:#c62828
    style Broker fill:#ffe0b2,stroke:#f57c00,stroke-width:2px,color:#e65100
    style Payment fill:#fffde7,stroke:#fbc02d,stroke-width:2px,color:#000
    style Client fill:#e3f2fd,stroke:#1e88e5,stroke-width:2px,color:#000
    style LLM fill:#f3e5f5,stroke:#8e24aa,stroke-width:2px,color:#000
